# Generated by Django 4.0.2 on 2022-02-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentassignment',
            name='assignment_status',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='assignment_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='assignment_desc',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='assignment_due_date',
            field=models.DateField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='assignment_instructions',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='assignment_name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_credits',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_school_id',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='educator',
            name='employee_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='school_id',
            field=models.IntegerField(default=0),
        ),
    ]
