# Generated by Django 4.0.2 on 2022-02-07 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_studentassignment_assignment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseassignment',
            name='assignment',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='assignment.assignment'),
        ),
        migrations.AlterField(
            model_name='courseassignment',
            name='course',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='assignment.course'),
        ),
        migrations.AlterField(
            model_name='educatorcourse',
            name='course',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='assignment.course'),
        ),
        migrations.AlterField(
            model_name='educatorcourse',
            name='educator',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='assignment.educator'),
        ),
        migrations.AlterField(
            model_name='studentassignment',
            name='assignment',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='assignment.assignment'),
        ),
        migrations.AlterField(
            model_name='studentassignment',
            name='student',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='assignment.student'),
        ),
        migrations.AlterField(
            model_name='studentcourse',
            name='course',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='assignment.course'),
        ),
        migrations.AlterField(
            model_name='studentcourse',
            name='student',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='assignment.student'),
        ),
    ]
