# Generated by Django 4.0.2 on 2022-02-09 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0004_alter_courseassignment_assignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assignment_course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='assignment.course'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='assignment_instructions',
            field=models.TextField(default=None),
        ),
        migrations.DeleteModel(
            name='CourseAssignment',
        ),
    ]
