# Generated by Django 4.0.2 on 2022-02-09 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0007_studentassignment_assignment_prev_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentassignment',
            name='assignment_prev_status',
            field=models.CharField(default='Not Started', max_length=50),
        ),
    ]
