# Generated by Django 4.0.2 on 2022-02-10 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0008_alter_studentassignment_assignment_prev_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='upload_to_folder_id',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
