# Generated by Django 4.0.2 on 2022-02-11 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0009_assignment_upload_to_folder_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='upload_to_folder_id',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
