# Generated by Django 4.0.2 on 2022-02-14 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0010_alter_assignment_upload_to_folder_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='educator',
            name='notepad_text',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='notepad_text',
            field=models.TextField(default=None, null=True),
        ),
    ]
