# Generated by Django 4.0.2 on 2022-02-17 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0011_educator_notepad_text_student_notepad_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='upload_to_folder_id',
            new_name='assignment_link',
        ),
    ]
