# Generated by Django 4.0.2 on 2022-02-17 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0012_rename_upload_to_folder_id_assignment_assignment_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assignment_link',
            field=models.TextField(default=None, null=True),
        ),
    ]
