# Generated by Django 4.0.2 on 2022-08-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0015_alter_assignment_assignment_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assignment_archived',
            field=models.BooleanField(default=False),
        ),
    ]
